In [1]:
import numpy as np
import csv
import pandas as pd

In [2]:
## 读取csv文件
data_train_origin = []
train = csv.reader(open('C:/Users/Administrator/Desktop/python_practice/Fudan_practice/text_classification_ML/train.tsv', 'rt'))
for row in train:
    data_train_origin.append(row)

data_test_origin = []
train = csv.reader(open('C:/Users/Administrator/Desktop/python_practice/Fudan_practice/text_classification_ML/test.tsv', 'rt'))
for row in train:
    data_test_origin.append(row)

In [3]:
## 数据的分割
data_train = []
for item in data_train_origin:
    if (len(item)>0):
        for j in range(1,len(item)):
            item[0]+=item[j]
    data_train.append(item[0].split('\t'))

data_test = []
for item in data_test_origin:
    if (len(item)>0):
        for j in range(1,len(item)):
            item[0]+=item[j]
    data_test.append(item[0].split('\t'))
    

In [4]:
## 删除标题
data_train.remove(data_train[0])
data_test.remove(data_test[0])

[[1,
  1,
  'A series of escapades demonstrating the adage that what is good for the goose is also good for the gander some of which occasionally amuses but none of which amounts to much of a story .',
  1],
 [2,
  1,
  'A series of escapades demonstrating the adage that what is good for the goose',
  2],
 [3, 1, 'A series', 2],
 [4, 1, 'A', 2],
 [5, 1, 'series', 2],
 [6,
  1,
  'of escapades demonstrating the adage that what is good for the goose',
  2],
 [7, 1, 'of', 2],
 [8,
  1,
  'escapades demonstrating the adage that what is good for the goose',
  2],
 [9, 1, 'escapades', 2],
 [10, 1, 'demonstrating the adage that what is good for the goose', 2],
 [11, 1, 'demonstrating the adage', 2],
 [12, 1, 'demonstrating', 2],
 [13, 1, 'the adage', 2],
 [14, 1, 'the', 2],
 [15, 1, 'adage', 2],
 [16, 1, 'that what is good for the goose', 2],
 [17, 1, 'that', 2],
 [18, 1, 'what is good for the goose', 2],
 [19, 1, 'what', 2],
 [20, 1, 'is good for the goose', 2],
 [21, 1, 'is', 2],
 [22, 1, '

In [12]:
## 简单预处理
for i in range(len(data_train)):
    data_train[i][0] = int(data_train[i][0])
    data_train[i][1] = int(data_train[i][1])
    data_train[i][2] = data_train[i][2].replace('  ',' ')
    data_train[i][3] = int(data_train[i][3])

for i in range(len(data_test)):
    data_test[i][0] = int(data_test[i][0])
    data_test[i][1] = int(data_test[i][1])
    data_test[i][2] = data_test[i][2].replace('  ',' ')

In [13]:
## 建立3元词袋模型来表征句子

# 切分单词
tokenized_lines = []
for item in data_train:
    tokenized_lines.append(item[2].split(' '))

In [14]:
# 去除标点，替换大小写
punctuation = [",", ":", ";", ".", "'", '"', "’", "?", "/", "-", "+", "&", "(", ")"]
clean_tokenized = []
for item in tokenized_lines:
    tokens = []
    for token in item:
        token = token.lower()
        for punc in punctuation:
            token = token.replace(punc, "")
        tokens.append(token)
    clean_tokenized.append(tokens)

[['a',
  'series',
  'of',
  'escapades',
  'demonstrating',
  'the',
  'adage',
  'that',
  'what',
  'is',
  'good',
  'for',
  'the',
  'goose',
  'is',
  'also',
  'good',
  'for',
  'the',
  'gander',
  'some',
  'of',
  'which',
  'occasionally',
  'amuses',
  'but',
  'none',
  'of',
  'which',
  'amounts',
  'to',
  'much',
  'of',
  'a',
  'story',
  ''],
 ['a',
  'series',
  'of',
  'escapades',
  'demonstrating',
  'the',
  'adage',
  'that',
  'what',
  'is',
  'good',
  'for',
  'the',
  'goose'],
 ['a', 'series'],
 ['a'],
 ['series'],
 ['of',
  'escapades',
  'demonstrating',
  'the',
  'adage',
  'that',
  'what',
  'is',
  'good',
  'for',
  'the',
  'goose'],
 ['of'],
 ['escapades',
  'demonstrating',
  'the',
  'adage',
  'that',
  'what',
  'is',
  'good',
  'for',
  'the',
  'goose'],
 ['escapades'],
 ['demonstrating',
  'the',
  'adage',
  'that',
  'what',
  'is',
  'good',
  'for',
  'the',
  'goose'],
 ['demonstrating', 'the', 'adage'],
 ['demonstrating'],
 ['th

In [16]:
# 生成原始的词汇集合,剔除了只出现过一次的token
unique_tokens = []
single_tokens = []
for tokens in clean_tokenized:
    for token in tokens:
        if token not in single_tokens:
            single_tokens.append(token)
        elif token in single_tokens and token not in unique_tokens:
            unique_tokens.append(token)

In [21]:
# 生成原始得二元词汇集合，剔除只出现过一次得token
unique_2_tokens = []
single_2_tokens = []
clean_2_tokenized = []
for tokens in clean_tokenized:
    token_2 = []
    for i in range(len(tokens)-1):
        token_2.append([tokens[i],tokens[i+1]])
    clean_2_tokenized.append(token_2)

for tokens in clean_2_tokenized:
    for token in tokens:
        if token not in single_2_tokens:
            single_2_tokens.append(token)
        elif token in single_2_tokens and token not in unique_2_tokens:
            unique_2_tokens.append(token)
    
        



In [25]:
# 生成原始得三元词汇集合，剔除只出现过一次得token
unique_3_tokens = []
single_3_tokens = []
clean_3_tokenized = []
for tokens in clean_tokenized:
    token_3 = []
    for i in range(len(tokens)-2):
        token_3.append([tokens[i],tokens[i+1],tokens[i+2]])
    clean_3_tokenized.append(token_3)

for tokens in clean_3_tokenized:
    for token in tokens:
        if token not in single_3_tokens:
            single_3_tokens.append(token)
        elif token in single_3_tokens and token not in unique_3_tokens:
            unique_3_tokens.append(token)

In [28]:
# 将二维的tokens转成一维tokens
all_tokens = []
for items in clean_tokenized:
    for item in items:
        all_tokens.append(item.lower())

In [31]:
# 将二维的tokens转成二元一维tokens
all_2_tokens = []
for items in clean_2_tokenized:
    for item in items:
        all_2_tokens.append(item)

In [34]:
# 将二维的tokens转成san元一维tokens
all_3_tokens = []
for items in clean_3_tokenized:
    for item in items:
        all_3_tokens.append(item)

In [72]:
# 统计每个词出现的频率
dic = {}
for token in unique_tokens:
    dic[token] = all_tokens.count(token)

In [62]:
# 统计每个二元词出现的频率
value_2 = []
for token in unique_2_tokens:
    value_2.append(all_2_tokens.count(token))
dic_2 = []
for i in range(len(value_2)):
    dic_2.append([all_2_tokens[i],value_2[i]])
    

In [64]:
# 统计每个三元词出现的频率
value_3 = []
for token in unique_3_tokens:
    value_3.append(all_3_tokens.count(token))
dic_3 = []
for i in range(len(value_3)):
    dic_3.append([all_3_tokens[i],value_3[i]])

In [95]:
# 筛选特征在5-50之间的一元特征
tokens = []
freq = []
for i in range(len(dic)):
    if list(dic.values())[i]>=5 and list(dic.values())[i]<=50:
        tokens.append(list(dic.keys())[i])
        freq.append(list(dic.values())[i])

In [96]:
# 筛选次数大于3的二元特征
tokens_2 = []
freq_2 = []
for i in range(len(dic_2)):
    if dic_2[i][1]>3:
        tokens_2.append(dic_2[i][0])
        freq_2.append(dic_2[i][1])

In [97]:
# 筛选次数大于3的三元特征
tokens_3 = []
freq_3 = []
for i in range(len(dic_3)):
    if dic_3[i][1]>3:
        tokens_3.append(dic_3[i][0])
        freq_3.append(dic_3[i][1])

In [109]:
# 将每个句子按照三元BOW特征空间进行表征
representations_1 =[]
representations_2 =[]
representations_3 =[]
representations =[]
for seq in clean_tokenized:
    rep = []
    for token in tokens:
        if token in seq:
            rep.append(1)
        else:
            rep.append(0)
    representations_1.append(rep)

for seq in clean_2_tokenized:
    rep = []
    for token in tokens_2:
        if token in seq:
            rep.append(1)
        else:
            rep.append(0)
    representations_2.append(rep)
    
for seq in clean_3_tokenized:
    rep = []
    for token in tokens_3:
        if token in seq:
            rep.append(1)
        else:
            rep.append(0)
    representations_3.append(rep)
representations = list(np.concatenate((np.concatenate((representations_1,representations_2),axis=1),representations_3),axis=1))

In [116]:
## 定义x，y
x = representations
y = []
for item in data_train:
    y.append(item[3])

In [117]:
## y生成one-hot vector
classes = np.max(y) + 1
y = np.eye(classes)[y]

In [118]:
## 划分集合
n_train = int(len(x)*0.8)
n_test = int(len(x)*0.1)
n_dev = int(len(x) - n_train -n_test)

import random
index_train = random.sample(range(len(x)),n_train)
index_dev = random.sample(list(set(range(len(x)))^set(index_train)) ,n_dev)
index_test = list(set(list(set(range(len(x)))^set(index_train)))^set(index_dev)) 

x_train = []
y_train = []
for index in index_train:
    x_train.append(x[index])
    y_train.append(y[index])
    
x_dev = []
y_dev = []
for index in index_dev:
    x_dev.append(x[index])
    y_dev.append(y[index])

x_test = []
y_test = []
for index in index_test:
    x_test.append(x[index])
    y_test.append(y[index])

x_train = np.array(x_train)
y_train = np.array(y_train)

x_dev = np.array(x_dev)
y_dev = np.array(y_dev)

x_test = np.array(x_test)
y_test = np.array(y_test)

In [288]:
## Logistic model
def logit(x_train,y_train,x_dev,y_dev,W,b,alpha,lam):
    y_ = 1/(1+np.exp(-np.dot(x_train,W)-b))
    y__dev = 1/(1+np.exp(-np.dot(x_dev,W)-b))
    loss = -np.average(y_train*np.log(y_)+(1-y_train)*np.log(1-y_))+lam/2*np.sum(W**2)
    loss_dev = -np.average(y_dev*np.log(y__dev)+(1-y_dev)*np.log(1-y__dev))+lam/2*np.sum(W**2)
    dloss_dW = -np.dot(x_train.T,(y_train-y_))/len(x_train)+lam*W
    dloss_db = -np.average(y_train-y_,axis = 0)
    W_new = W - alpha*dloss_dW
    b_new = b - alpha*dloss_db
    return loss,loss_dev, W_new, b_new

In [453]:
## 批量梯度下降法：
def bat_gradesc(x_train,y_train,x_dev,y_dev,W,b,alpha,lam):
    losses = []
    losses_dev = []
    iteration = 0
    num = 0
    while (num<10 and iteration < 5000):
        loss,loss_dev, W, b = logit(x_train,y_train,x_dev,y_dev,W,b,alpha,lam)
        losses.append(loss)
        losses_dev.append(loss_dev)
        iteration += 1
        if  (len(losses_dev)>=2):
            if (loss_dev-losses_dev[-2]>0):
                num += 1
            else:
                num = 0
        print(str(iteration)+' iteration:')
        print(num)
    return losses, losses_dev, W, b, iteration

In [173]:
## 随机梯度下降法：
def st_gradesc(x_train,y_train,x_dev,y_dev,W,b,alpha,lam):
    losses = []
    losses_dev = []
    iteration = 0
    num = 0
    while (num<10 and iteration < 5000):
        rand = random.randint(0,len(x_train)-1)
        x_rand = np.array(x_train[rand])
        x_rand = x_rand.reshape([1,len(x_rand)])
        y_rand = np.array(y_train[rand])
        y_rand = y_rand.reshape([1,len(y_rand)])
        loss,loss_dev, W, b = logit(x_rand,y_rand,x_dev,y_dev,W,b,alpha,lam)
        losses.append(loss)
        losses_dev.append(loss_dev)
        iteration += 1
        if  (len(losses_dev)>=2):
            if (loss_dev-losses_dev[-2]>0):
                num += 1
            else:
                num = 0
        print(str(iteration)+' iteration:')
        print(num)
    return losses, losses_dev, W, b, iteration   

In [221]:
## 小批量梯度下降法：
def min_gradesc(x_train,y_train,x_dev,y_dev,W,b,alpha,lam):
    losses = []
    losses_dev = []
    iteration = 0
    num = 0
    while (num<10 and iteration < 5000):
        x_rand = np.array(random.sample(list(x_train),20))
        y_rand = np.array(random.sample(list(y_train),20))
        loss,loss_dev, W, b = logit(x_rand,y_rand,x_dev,y_dev,W,b,alpha,lam)
        losses.append(loss)
        losses_dev.append(loss_dev)
        iteration += 1
        if  (len(losses_dev)>=2):
            if (loss_dev-losses_dev[-2]>0):
                num += 1
            else:
                num = 0
        print(str(iteration)+' iteration:')
        print(num)
    return losses, losses_dev, W, b, iteration 

In [467]:
## 计算accuracy
def evaluate(W,b,lam,x_test,y_test):
    y = []
    for onehot in y_test:
        y.append(np.where(onehot > 0.5)[0][0])
    y_pre = y__dev = 1/(1+np.exp(-np.dot(x_test,W)-b))
    y_ = []
    for vector in y_pre:
        y_.append(np.where(vector == max(vector))[0][0])
    loss = -np.average(y_test*np.log(y_pre)+(1-y_test)*np.log(1-y_pre))+lam/2*np.sum(W**2)
    accuracy = float(np.sum(np.array(y)==np.array(y_)))/float(len(y))
    precision = []
    recall = []
    f1 = []
    elems = list(set(y))
    for elem in elems:
        p = 0
        r = 0
        n = 0
        for i in range(len(y)):
            if (y[i] == elem):
                p += 1
            if (y_[i] == elem):
                r += 1
            if (y[i] == y_[i] and y[i] == elem):
                n +=1
        if (p != 0):
            precision.append(float(n)/float(p))
        else:
            precision.append(0)
        if (r != 0):
            recall.append(float(n)/float(r))
        else:
            recall.append(0)
    for j in range(len(precision)):
        if (precision[j]!=0 or recall[j] != 0):
            f1.append(2*precision[j]*recall[j]/(precision[j]+recall[j]))
        else:
            f1.append(0)
    return loss, accuracy,elems,precision,recall,f1,y,y_

In [452]:
## 初始化参数，logistic model可以全0初始化
W = np.zeros([np.shape(x_train)[1],np.shape(y_train)[1]])
b = np.zeros([1,np.shape(y_train)[1]])

In [460]:
## 运行迭代
losses, losses_dev, W, b, iteration = bat_gradesc(x_train,y_train,x_dev,y_dev,W,b,0.000001,0.2)

1 iteration:
0
2 iteration:
0
3 iteration:
0
4 iteration:
0
5 iteration:
0
6 iteration:
0
7 iteration:
0
8 iteration:
0
9 iteration:
0
10 iteration:
0
11 iteration:
0
12 iteration:
0
13 iteration:
0
14 iteration:
0
15 iteration:
0
16 iteration:
0
17 iteration:
0
18 iteration:
0
19 iteration:
0
20 iteration:
0
21 iteration:
0
22 iteration:
0
23 iteration:
0
24 iteration:
0
25 iteration:
0
26 iteration:
0
27 iteration:
0
28 iteration:
0
29 iteration:
0
30 iteration:
0
31 iteration:
0
32 iteration:
0
33 iteration:
0
34 iteration:
0
35 iteration:
0
36 iteration:
0
37 iteration:
0
38 iteration:
0
39 iteration:
0
40 iteration:
0
41 iteration:
0
42 iteration:
0
43 iteration:
0
44 iteration:
0
45 iteration:
0
46 iteration:
0
47 iteration:
0
48 iteration:
0
49 iteration:
0
50 iteration:
0
51 iteration:
0
52 iteration:
0
53 iteration:
0
54 iteration:
0
55 iteration:
0
56 iteration:
0
57 iteration:
0
58 iteration:
0
59 iteration:
0
60 iteration:
0
61 iteration:
0
62 iteration:
0
63 iteration:
0
6

In [476]:
## 模型评估
loss,accuracy,elems,precision,recall,f1,y,y_ = evaluate(W,b,0.2,x_test,y_test)

In [477]:
loss

0.69158927231522527

In [478]:
accuracy

0.62

In [479]:
elems

[1, 2, 3, 4]

In [480]:
recall

[0, 0.62, 0, 0]

In [ ]:
    y_ = 1/(1+np.exp(-np.dot(x_train,W)-b))
    y__dev = 1/(1+np.exp(-np.dot(x_dev,W)-b))
    loss = -np.average(y_train*np.log(y_)+(1-y_train)*np.log(1-y_))+lam/2*np.sum(W**2)
    loss_dev = -np.average(y_dev*np.log(y__dev)+(1-y_dev)*np.log(1-y__dev))+lam/2*np.sum(W**2)
    dloss_dW = -np.dot(x_train.T,(y_train-y_))/len(x_train)+lam*W
    dloss_db = -np.average(y_train-y_,axis = 0)
    W_new = W - alpha*dloss_dW
    b_new = b - alpha*dloss_db

In [446]:
y_ = 1/(1+np.exp(-np.dot(x_train,W)-b))

In [447]:
y_

array([[ 0.42242721,  0.44724455,  0.51491803,  0.44249253,  0.42546765],
       [ 0.43384264,  0.44853445,  0.51806209,  0.4518175 ,  0.43869879],
       [ 0.42235755,  0.45246836,  0.51202465,  0.44036571,  0.42712759],
       ..., 
       [ 0.43335981,  0.44943506,  0.51788156,  0.45097054,  0.43786093],
       [ 0.43371582,  0.44909761,  0.5178707 ,  0.45097907,  0.43787141],
       [ 0.4348281 ,  0.44954158,  0.51807974,  0.45212394,  0.43933955]])

In [448]:
y__dev = 1/(1+np.exp(-np.dot(x_dev,W)-b))

In [449]:
y__dev

array([[ 0.43164875,  0.44831725,  0.51840126,  0.44850315,  0.43544709],
       [ 0.434173  ,  0.45028014,  0.51735615,  0.45145219,  0.4386802 ],
       [ 0.43470879,  0.4497582 ,  0.51717945,  0.45128659,  0.43851674],
       [ 0.4348281 ,  0.44954158,  0.51807974,  0.45212394,  0.43933955],
       [ 0.28544776,  0.37554537,  0.58752091,  0.30348985,  0.29284755],
       [ 0.40979207,  0.42732369,  0.52634872,  0.43919715,  0.41310818],
       [ 0.42494907,  0.44879421,  0.51534695,  0.44405124,  0.43009027],
       [ 0.43435449,  0.4490523 ,  0.51753461,  0.45268515,  0.43886282],
       [ 0.43134234,  0.44617341,  0.51846867,  0.44782866,  0.4365328 ],
       [ 0.43388171,  0.44926653,  0.51805147,  0.45079598,  0.43803853],
       [ 0.43154763,  0.44618795,  0.51837695,  0.45157462,  0.43638797],
       [ 0.42723405,  0.44455368,  0.5219953 ,  0.44501489,  0.43135257],
       [ 0.43369739,  0.44873077,  0.51752137,  0.45201735,  0.43854788],
       [ 0.43417206,  0.44887133,  0.5

In [451]:
y_dev

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  

In [434]:
loss = -np.average(y_train*np.log(y_)+(1-y_train)*np.log(1-y_))+0.2/2*np.sum(W**2)

In [435]:
loss

0.6184408366242018

In [436]:
loss_dev = -np.average(y_dev*np.log(y__dev)+(1-y_dev)*np.log(1-y__dev))+0.2/2*np.sum(W**2)

In [437]:
loss_dev

0.63208104866479642

In [438]:
dloss_dW = -np.dot(x_train.T,(y_train-y_))/len(x_train)+0.2*W

In [439]:
dloss_dW

array([[ 0.00767183,  0.00575927, -0.00191498,  0.00578166,  0.00554624],
       [ 0.00667565,  0.0069404 , -0.00302697,  0.00250433,  0.00675152],
       [ 0.00099673,  0.00102675,  0.00116594, -0.0012265 ,  0.00100589],
       ..., 
       [ 0.00097674,  0.00100753,  0.00115443,  0.00102069, -0.00126125],
       [ 0.00097674,  0.00100753,  0.00115443,  0.00102069, -0.00126125],
       [ 0.00097674,  0.00100753,  0.00115443,  0.00102069, -0.00126125]])

In [440]:
dloss_db = -np.average(y_train-y_,axis = 0)

In [441]:
dloss_db

array([ 0.40305284,  0.31240982, -0.11012436,  0.2939168 ,  0.37430715])

In [442]:
W = W - 0.1*dloss_dW

In [443]:
W

array([[-0.00527439, -0.00395946,  0.00131629, -0.00396319, -0.00388947],
       [-0.00460646, -0.0046908 ,  0.00202615, -0.00186159, -0.00463022],
       [-0.00067198, -0.0006814 , -0.00072473,  0.00074362, -0.00067483],
       ..., 
       [-0.00066558, -0.0006753 , -0.00072126, -0.00067929,  0.00075461],
       [-0.00066558, -0.0006753 , -0.00072126, -0.00067929,  0.00075461],
       [-0.00066558, -0.0006753 , -0.00072126, -0.00067929,  0.00075461]])

In [444]:
b = b - 0.1*dloss_db

In [445]:
b

array([[-0.26217913, -0.20252307,  0.07235051, -0.19209274, -0.24384287]])